local completion_plugin = 'coc' -- 'coc' or 'lsp'
local config_folder = string.format('%s_config', completion_plugin)
require(string.format('%s', config_folder))
require(string.format('%s.keymaps', config_folder))
require(string.format('%s.plugins.autopairs', config_folder))
require(string.format('%s.plugins.catppuccin', config_folder))
require(string.format('%s.plugins.comment', config_folder))
require(string.format('%s.plugins.debugger', config_folder))
require(string.format('%s.plugins.lualine', config_folder))
require(string.format('%s.plugins.nvim-tree', config_folder))
require(string.format('%s.plugins.packer', config_folder))
require(string.format('%s.plugins.telescope', config_folder))
require(string.format('%s.plugins.toggleterm', config_folder))
require(string.format('%s.plugins.treesitter', config_folder))
require(string.format('%s.plugins.undotree', config_folder))
require(string.format('%s.plugins.which-key', config_folder))
require(string.format('%s.plugins.gitsigns', config_folder))
require(string.format('%s.plugins.mini-starter', config_folder))
pcall(require, string.format('%s.plugins.lsp', config_folder))
pcall(require, string.format('%s.plugins.cmp', config_folder))
pcall(require, string.format('%s.plugins.coc', config_folder))
